### ISSUE TITLE
Get separated H and E channels

### ISSUE THREAD

**Issue by zalteck** [Zhengyushan/adaptive_color_deconvolution#1]
Dear Yushan Zheng,

I'd like to get the separated H&E bands obtained by your method. Which is the correct way to do that using your code?

Thank you very much.

**Comment by Zhengyushan** [comment]
Thanks for your attention. I have added a function to output the H&E channels. Please find the example at the bottom of main.py

**Comment by zalteck** [comment]
Thank you very much.
